spring.application.name=splitbill

# H2 DB config
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.session.store-type=none

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console