spring.application.name=splitbill

spring.session.store-type=none

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.config.import=optional:file:./src/main/resources/secret.properties

server.port=${PORT:8080}
allowed-origins=${ALLOWED_ORIGIN}
stripe.secret-key=${STRIPE_SECRET}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
stripe.price-id=${STRIPE_PRICE_ID}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}